### ISSUE TITLE
Error on "Set color theme"

### ISSUE THREAD

**Issue by maurelian** [tintinweb/vscode-solidity-auditor#13] opened 2019-04-08 20:19 UTC
When I click on 'set color theme':

![image](https://user-images.githubusercontent.com/23033765/55754087-e12cc280-5a19-11e9-9d05-d0ebcd26de47.png)

I get this error message:

![image](https://user-images.githubusercontent.com/23033765/55754119-eab62a80-5a19-11e9-96fe-b84c960bb383.png)

TBH I'm not really sure what that button should do.

**Comment by maurelian** [comment] 2019-04-08 20:21
The button works if I first manually set the color theme to one of the extension's themes.

**Comment by tintinweb** [comment] 2019-04-09 10:24
I didn't even know that button. probably easy to fix but low prio.

**Comment by cleanunicorn** [comment] 2019-04-11 07:06
The button helps you choose between the light and dark color theme. Works for me in the `0.0.14` version.
![image](https://user-images.githubusercontent.com/547012/55937343-6b0aa480-5c41-11e9-9f23-c8bdeeca87c4.png)

**Comment by tintinweb** [comment] 2019-07-14 18:35
closing this one as cannot not reproduce.

**Closed by tintinweb** 2019-07-14 18:35 UTC
Labels: PRIO:LOW, bug
